### ISSUE TITLE
Toasts.showToast()方法第二个Toast无法显示

### ISSUE THREAD

**Issue by 632610503** [hyzhan43/KtWing#1]
连续点击的话只会弹出第一个Toast，之后的不会再显示，9.0版本Toast源码问题  
[Android 9.0 Toast源码改变引发的问题](https://blog.csdn.net/qq_36486247/article/details/102753801?depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-3&utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-3)

**Comment by hyzhan43** [comment]
好的，代码已修复，谢谢你提醒 ：）
